fix(FEC-13628): markers not shown on timeline for clipped video
kaltura/playkit-js-timeline pull request #32
Opened 2024-02-07 10:23 UTC by lianbenjamin

### Description of the Changes

- **bugfix**

**the issue:**
sometimes markers/chapters are not shown on timeline.

**root cause:**
when checking if the duration is correct, it is possible that `seekFrom` has value of `0`.
currently, when the value is 0, the logic breaks and the new calculation for duration is not happening. As a result, the duration is never correct and `timelineDurationPromise` is never resolved. This affect rendering cuepoints on timeline.

**solution:**
validate `typeof seekFrom`.

Solves [FEC-13628](https://kaltura.atlassian.net/browse/FEC-13628)

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2024-02-07 10:29 UTC, SivanA-Kaltura requested changes

2024-02-07 10:29 UTC, SivanA-Kaltura commented on src/timeline-manager.tsx
> +    if (clipTo && typeof seekFrom === 'number') {
is clipTo guaranteed to be a number ?

2024-02-07 10:31 UTC, lianbenjamin commented on src/timeline-manager.tsx
> +    if (clipTo && typeof seekFrom === 'number') {
clipTo is string or undefined

2024-02-08 11:33 UTC, semarche-kaltura approved these changes

2024-02-12 15:24 UTC, merged